### ISSUE TITLE
Getting error running -  yo react-webpack-redux:action

### ISSUE THREAD

**Issue by laitang2000** [stylesuxx/generator-react-webpack-redux#10]
Hi, 
Using the latest I'm getting the following error when attempting to run yo react-webpack-redux:action test

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Line 17: Unexpected token -
    at throwError (C:\Users\laita\AppData\Roaming\npm\node_modules\generator-react-webpack-redux\node_modules\esprima-fb\esp
rima.js:2819:21)
    at throwUnexpected (C:\Users\laita\AppData\Roaming\npm\node_modules\generator-react-webpack-redux\node_modules\esprima-f
b\esprima.js:2881:9)
    at expect (C:\Users\laita\AppData\Roaming\npm\node_modules\generator-react-webpack-redux\node_modules\esprima-fb\esprima
.js:2890:13)
    at parseObjectInitialiser (C:\Users\laita\AppData\Roaming\npm\node_modules\generator-react-webpack-redux\node_modules\es
prima-fb\esprima.js:3430:17)
    at parseVariableDeclaration (C:\Users\laita\AppData\Roaming\npm\node_modules\generator-react-webpack-redux\node_modules\
esprima-fb\esprima.js:4815:18)
    at parseVariableDeclarationList (C:\Users\laita\AppData\Roaming\npm\node_modules\generator-react-webpack-redux\node_modu
les\esprima-fb\esprima.js:4855:23)
    at parseConstLetDeclaration (C:\Users\laita\AppData\Roaming\npm\node_modules\generator-react-webpack-redux\node_modules\
esprima-fb\esprima.js:4886:24)
    at parseSourceElement (C:\Users\laita\AppData\Roaming\npm\node_modules\generator-react-webpack-redux\node_modules\esprim
a-fb\esprima.js:6439:24)
    at parseFunctionSourceElements (C:\Users\laita\AppData\Roaming\npm\node_modules\generator-react-webpack-redux\node_modul
es\esprima-fb\esprima.js:5791:29)
    at parseConciseBody (C:\Users\laita\AppData\Roaming\npm\node_modules\generator-react-webpack-redux\node_modules\esprima-
fb\esprima.js:5738:20)

Cheers

**Comment by stylesuxx** [comment]
This is most possibly related to #11 I could imagine,...

**Comment by stylesuxx** [comment]
Can you please tell me which node version you are using exactly?

**Comment by cca313** [comment]
when i run "npm start " after "yo react-webpack-redux" finished

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'serve' ]
2 info using npm@3.3.12
3 info using node@v5.3.0
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle webpackdemo@0.0.1~preserve: webpackdemo@0.0.1
6 silly lifecycle webpackdemo@0.0.1~preserve: no script for preserve, continuing
7 info lifecycle webpackdemo@0.0.1~serve: webpackdemo@0.0.1
8 verbose lifecycle webpackdemo@0.0.1~serve: unsafe-perm in lifecycle true
9 verbose lifecycle webpackdemo@0.0.1~serve: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\webpackdemo\node_modules\.bin;F:\oracle\product\10.2.0\client_1\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\TortoiseGit\bin;C:\Users\Administrator\.dnx\bin;C:\Users\Administrator\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin
10 verbose lifecycle webpackdemo@0.0.1~serve: CWD: E:\webpackdemo
11 silly lifecycle webpackdemo@0.0.1~serve: Args: [ '/d /s /c', 'node server.js --env=dev' ]
12 silly lifecycle webpackdemo@0.0.1~serve: Returned: code: 1  signal: null
13 info lifecycle webpackdemo@0.0.1~serve: Failed to exec serve script
14 verbose stack Error: webpackdemo@0.0.1 serve: `node server.js --env=dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid webpackdemo@0.0.1
16 verbose cwd E:\webpackdemo
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
19 error node v5.3.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error webpackdemo@0.0.1 serve: `node server.js --env=dev`
22 error Exit status 1
23 error Failed at the webpackdemo@0.0.1 serve script 'node server.js --env=dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the webpackdemo package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server.js --env=dev
23 error You can get their info via:
23 error     npm owner ls webpackdemo
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by stylesuxx** [comment]
Summoning @zerocity to take a look at this under Windows.

**Comment by glcheetham** [comment]
As I commented in #13 everything works well for me under Windows 10
```
>node --version
v4.3.2
```

**Comment by stylesuxx** [comment]
Awesome, thank you @glcheetham for the feedback, closing this down.

Feel free to reopen if you into this problem and can provide more info.
