### ISSUE TITLE
Wrong paths when generating actions and reducers in Windows

### ISSUE THREAD

**Issue by nachaescudero** [stylesuxx/generator-react-webpack-redux#11]
When generating actions in Windows SO the path generated in containers/App.js are in windows' path format: "`..\\actions\\name.js`".
Same error occure when generating reducers, in the reducers/index.js

**Comment by stylesuxx** [comment]
I am using the path module to generate those paths. I have currently no access to a Windows machine, do you think you could provide a PR fixing this issue? If not I will try to get hold of a Windows machine some time next week.

**Comment by nachaescudero** [comment]
Thanks for the response. I will try to fix it later today and make the PR.

**Comment by stylesuxx** [comment]
Thank you, that would really be awesome :-)

**Comment by stylesuxx** [comment]
Alright, merged your additions and released a new version, thank you for your contribution.

**Comment by nachaescudero** [comment]
Happy to help :)
