### ISSUE TITLE
Why use 'Component' suffix while it is not a redux conventions ? 

### ISSUE THREAD

**Issue by l1br3** [stylesuxx/generator-react-webpack-redux#15]
Hi, 

Everything is in the title. As the namespace and the component module nature is already contained in the import/require statement, why did you choose to add this suffix ? 

Note that it is just a question, I'm a very beginner with react/redux and I'm surprised by this difference between the redux documentation and the generator.

Have a nice day

**Comment by stylesuxx** [comment]
This generator is build on top of [another generator](https://github.com/newtriks/generator-react-webpack) and just extends it for Redux functionality.

The other generator handles the creation of components, and thus the components are named the way they are.

But it is an interesting question regarding the conventions. Give me some time to think about this.

**Comment by sthzg** [comment]
FWIW, I've recently stumbled upon discussion about the `Component` suffix on the original generator as well: https://github.com/newtriks/generator-react-webpack/issues/186 . There seem to be plans to drop it in 4.0 release.

**Comment by prisonier** [comment]
I also think about this and I think it could be a good practice to keep it for the upcoming container generator.

I think that the conainer generator could be used like this : 

```bash
#component
yo react-webpack-redux:component my/namespaced/components/name

#container
yo react-webpack-redux:container my/namespaced/components/name
```

Note that I kept the component/name in the container generator, this is not an error.
As I'm very new to react/redux, I'm don't know if containers are always paired with components but it is what I understood from redux todo app tutorial.

By setting the same container/component name, the container could be very easily generated : 

```javascript
// generated with : yo react-webpack-redux:container todo/link
// containers/todo/LinkContainer.js - replace FilterLink.js from the todo app tutorial


import { connect } from 'react-redux'
import Link from '../../components/todo/LinkComponent' // Even the path depth could be generated

const mapStateToProps = (state, ownProps) => {
  return {
    // Here add your own state
  }
}

const mapDispatchToProps = (dispatch, ownProps) => {
  return {
    // Here add your own dispatchs
  }
}

const LinkContainer = connect(
  mapStateToProps,
  mapDispatchToProps
)(LinkComponent)

export default LinkContainer
```

This way, the "Component" suffix has a clear usage and is useful to generate containers with a "Container" suffix.

Note: This is a very noob approch, I only did the todo app tutorial

**Comment by stylesuxx** [comment]
Thanks @sthzg I'll keep an eye on those changes.

Regarding the container VS component:
*Components* are driven by props and are basically *unaware of Redux*. They only care about their props being set.

*Containers* are "less" dumb components, so they are *aware of Redux* and *coupled more tightly* to the app.

So there is no 1:1 relationship between components and containers.
A container - as the name suggests - is a container for components, setting up everything to pass straight down to its Components.

Hope that helps.

Btw, the container generator is still on the Todo list, so if you want to submit a PR, I would appreciate it.

**Comment by prisonier** [comment]
So if there is not always a container for a composant, can we say that there is always a component for a container ? If so, do you agree with the implementation I suggested ? 
But do we still keep "Component"/"Container" suffixes if they will be removed from next version of the underlying generator ?

**Comment by stylesuxx** [comment]
Technically a container would not make sense without components to hold.
IMHO I would drop the suffix for containers, since it will be dropped for components I think this would be the consistent thing to do.

Give me some time to think about it thoroughly.

**Comment by stylesuxx** [comment]
Seems the component suffix will be dropped in the next release of the base generator.

**Comment by stylesuxx** [comment]
Alright, the suffix has been dropped in the base generator. Will be part, or in this case, lacking in the next release.
