### ISSUE TITLE
Duplicated state declaration for mapStateToProps : don't cause any problem ?

### ISSUE THREAD

**Issue by prisonier** [stylesuxx/generator-react-webpack-redux#17]
As you know I'm not familiar with redux.

When I follow the redux todo app tutorial, there is nothing like container/App.js so I tried to improvise... and it worked !

I generated the reducers with this awesome genrators and I get something like that in my App.js : 

```javascript
// containers/App.js
function mapStateToProps(state) {
  /* Populated by react-webpack-redux:reducer */
  const props = {
    todos: state.todos
  };
  return props;
}
```

Then I created the VisibleTodoList.js container which also have a mapStateToProp: 
```javascript
function mapStateToProps (state) {
  return {
    todos: getVisibleTodos(state.todos, state.visibilityFilter)
  }
}
```

First I see that even if the app has twice 'todos' in mapStateToProps, the todo items are correctly filtered but I'm not sure to understand the data flow and why it does not cause any conflicts. 

Is it because App.js is in an higher "scope" level from VisibleTodoList.js and the todos state get overwrited ?

Thanks

**Comment by stylesuxx** [comment]
Hmm, where did you hook up your container?
Maybe you could make a repo for your project so I can take a look at the code directly? I am not sure if I am following your question, and some source is better than a 1000 words ;-)

**Comment by prisonier** [comment]
Sorry dude I totally forget to do that.

[Find here the MapStateToProps in the App.js](https://github.com/prisonier/redux-container-test/blob/master/src/containers/App.js#L34)
[And here the MapStateToProps in the VisibleTodoList.js](https://github.com/prisonier/redux-container-test/blob/master/src/containers/todo/VisibleTodoList.js#L19)

Both are referencing "todos" but in different ways and I don't understand what is the data flow or if I should remove the one from App.js.

**Comment by stylesuxx** [comment]
OK, I too a look at your app.

First of all, take a look at your [todos reducer](https://github.com/prisonier/redux-container-test/blob/master/src/reducers/todo/todos.js), something is strage there, you have two switch statements.

If you take a look at the *ADD_TODO* statement (in the first switch) you should be returning a list of objects, but you are returning an object.

In the reducer you should return the state, this has to be in the same form as the initial state. Also you should not mutate the passed state, but rather make a copy, change what you need to change and return that.

In the Main component you render the *ToDoApp* Component, in which you render two containers, *AddTodo* and *VisibleTodoList*.

*AddTodo* should be simply a **component** that, when the button is clicked triggers an *ADD_TODO* action and passes the content of the from.

Same goes for *VisibleTodoList* and *FilterLink*, I don't quite get why they are containers.

So to make it short, what are all those containers that are *not* implement a Class that extends *Component*?

I would structure it like so:

App Container
- Todo Form component (triggers *Add Todo* action)
- Filter component (triggers *Set Visibility* action)
- Todo List component (Renders todo list items based on visibility)

Todo Item Component (triggers *toggle* and *add* Todo action)

One Todo Reducer handling the following actions:
- Add Todo
- Toggle Todo
- Remove Todo

One "Global" Reducer to handle the visibility actions:
- Set visibility

App container passes the todos and the global state to the Todo List component which then decides based on the global state visibility filter which items to render in the list.

Each Todo item needs to be passed the action for toggle and remove, which it then triggers when invoked.

The filter component only needs to be passed the current filter state.

**Comment by prisonier** [comment]
I think I better understand your structure rather than the one I implemented but I didn't invented it, it is exactly the same as in [the official redux tutorial](http://redux.js.org/docs/basics/ExampleTodoList.html).

1. The both switch in todos reducer : one is for return a new single todo item and the other (the exported, the second) is to return the new state which contains all the todo items. 

2. I don't get where I'm mutating the existing state, I always return new objects or array. Once again, everything comes from the official tutorial. The first switch returns single objects that the second switch uses to return new array.

3. I neither understand why *AddTodo* is a container, there any logic inside but.... the tutorial ! Sorry, I don't see any anchor in their website to show you directly the files.

4. According to the tutorial, *VisibleTodoList* and *FilterLink* are containers because neither *Link* and *TodoList* components should be aware of what happen onClick. Those containers are wrappers for *active* and *todos* state and onClick actions (*onClick* and *onTodoClick*).

5. According to the tutorial, everything should be simple function and we should use class only when it is absolutely necessary. To be totally honest, I don't get that point because I don't really know what is the practical difference in class/function usage. I know all the theory about classes (I used Java) but I don't understand what happen here.

What I understand with your structure is that you will put business logic in components because they will know which action you dispatch whereas Dan Abramov recommend to use a container for each component which needs logic (like actions to dispatch or filtered states). The main argument is for component reusability: if they just have an *onClick* action, you can reuse them everywhere, but seriously, your structure is much more understandable !

Now I think you understand the title of this issue, the generator automatically create mapStateToProps than I recreate in tutorial containers.

**Comment by stylesuxx** [comment]
1.  I understand, it was just confusing for me, I always put a single reducer in one File, but that is OK too.
2. You are right, you are not mutating it anywhere, seems I was tired already ;-)
3. Hmm, I need to look into this, this does not really make sense for me right now.
4. I don't get this one either. If I have a component, and pass that component an action as a prop, the component does not do any business logic, it just knows, when that button is clicked, invoke that action that was passed in the props. Component is still reusable.
5. Need to read up on that as well - does not make too much sense to me.

That said, I think there is no "one right" way to do it. I quickly implemented a Todo app yesterday in the way I suggested it before, I will up it later so you can take a look.

I will take a look at the points that do not make sense to me and keep you posted.

**Comment by stylesuxx** [comment]
**3.** AddTodo is simply a container because they need to import the addTodo action. If they made that a component, they would break the reusability of it.

**4.** Their entry point for the app is a component. Inside that component they have two containers, one for adding a component and one for displaying the list.

In the containers they set up what needs to be passed down to the components. IMHO this is a bit over engineered in this case, since the app could be a container and propagate all the props down to it's components as they need them.

**5.** I think the idea behind this is to encourage people not to have state in their components, since this is just a function returning DOM elements, you can't really fuck anything up there. Makes sense to some degree, but since I am using the component generator of the base generator I do not really have influence on how it is generated.

We could think about adding a generator that is called *dumb-component* that will generate a Component that is only a function.

And to close the cycle to the original question:
The store is passed through the provider, so it exists only once.
It basically listens for actions being dispatched and passes them to the reducers, which then to their stuff to modify the current state of the app.
Where those actions are dispatched does not really matter, they just need to be from elements "under" the provider.

**Comment by prisonier** [comment]
**3**. So it's the same for *FilterLink* and *VisibleTodoList*, they also import actions. 

**4**. Having one main container and pass states and props to childs is the implementation you choose for the generator right ?

**5**. Got it. Initialy Dan Abramov called it *dumb component* and finally *representational component*. I don't know if it is necessary to create a new generator: redux convention are not **really** followed but things works fine. Plus it would be confusing to have 2 generators for the same thing.
Extending the React.component class add more features than a simple function I guess ?

Ok, the store exists only once. 
The point I still don't get is that the *todos* state is defined twice in 2 files but it is still the filtered state which is displayed. Is it because the filtered state is defined in a child of the App container (which has the unfiltered state).

The actions arn't dispatched twice as they are defined in 2 containers ?

**Comment by stylesuxx** [comment]
*4.* Yep, exactly. In my use cases I never had the need for more than one container - yet.
*5.* Yeah, you have more functionality when extending the class. There are various methods you can overwrite, for example componentDidMount, which is run once when the component has been mounted.

The more I think about it now, the more it makes sense and I tend in the direction of changing the component generator - so thanks for that ;-)

Hmm, I do not quite get where the todo state is defined twice. The todos are in the store, which only exists once,... The mapping to the props is there multiple times:
* In `getVisibleTodos` the prop *todos* is set to the visible todos by filtering the todos from the apps store.
* In 'App.js' where they are simply mapped 1:1 from the store.

And you can map store values as often as you want, you do not change them by mapping them to props.

The store is the single source of truth for the app, and is only changed by the reducers that handle triggered actions, the reducers then return the *nextState* of whatever they are responsible for, the store then updates to nextState and propagates the changes down to the app, which propagates to the container. The container then takes the current state (or parts of it) and passes the props down to the components that need them.

**Comment by stylesuxx** [comment]
Closing this down for lack of activity, feel free to reopen if there are any further questions.

**Comment by prisonier** [comment]
Sorry I forget to reply to this but the question has been crearly answer IMHO. Thanks for your help.
