### ISSUE TITLE
Any plan to implement an express server ?

### ISSUE THREAD

**Issue by prisonier** [stylesuxx/generator-react-webpack-redux#19]
Did you think about using express in server.js to make this generator production ready ?

**Comment by stylesuxx** [comment]
Yes, in fact I did. But not in this generator. I wanted to build a generator on top of this generator that adds express and graphql into the mix.

**Comment by prisonier** [comment]
Would be nice !

**Comment by stylesuxx** [comment]
Closing this down. You can follow me if you'd like, then you'll get updated as soon as I release this.

**Comment by prisonier** [comment]
for sure :)
