### ISSUE TITLE
The component generator doesn't work without generator-react-webpack

### ISSUE THREAD

**Issue by louisremi** [stylesuxx/generator-react-webpack-redux#2]
Hi, I'm giving this generator a try but couldn't get the component generator to work without installing generator-react-webpack first, which isn't stated in the docs.

Running `yo react-webpack-redux:component AddItem` resulted in
`You don't seem to have a generator with the name react-webpack:component installed.` error message (note the **react-webpack**:component).

After looking at the source and doing a quick `npm install -g generator-react-webpack` I was able to use either `yo react-webpack-redux:component AddItem` or `yo react-webpack:component AddItem` to create components.

Very nice tool anyway, keep up the great work!

**Comment by stylesuxx** [comment]
Thank you for submitting this issue. I will take a look and update accordingly this week.

**Comment by stylesuxx** [comment]
This should be fixed now. Feel free to reopen if problem persists.
Published to npm as version **0.4.0**
