### ISSUE TITLE
Getting error when create new reduce?

### ISSUE THREAD

**Issue by Riokai** [stylesuxx/generator-react-webpack-redux#20]
run`yo react-webpack-redux:reducer test ` and I got a error
```shell
Error: ENOENT: no such file or directory, open '/Users/zengkai/Code/Project/my-new-project/src/reducers/index.js'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.read (/usr/local/lib/node_modules/generator-react-webpack-redux/generators/app/utils.js:14:19)
    at attachToRoot (/usr/local/lib/node_modules/generator-react-webpack-redux/generators/reducer/index.js:24:24)
    at module.exports.generator.Base.extend.writing (/usr/local/lib/node_modules/generator-react-webpack-redux/generators/reducer/index.js:123:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-react-webpack-redux/node_modules/yeoman-generator/lib/base.js:436:25)
    at /usr/local/lib/node_modules/generator-react-webpack-redux/node_modules/run-async/index.js:26:25
    at /usr/local/lib/node_modules/generator-react-webpack-redux/node_modules/run-async/index.js:25:19
    at /usr/local/lib/node_modules/generator-react-webpack-redux/node_modules/yeoman-generator/lib/base.js:448:8
➜  my-new-project mkdir src/reducers && touch src/reducers/index.js
```

if I create two files
```shell
mkdir src/reducers && touch src/reducers/index.js 
mkdir src/containers && touch src/containers/App.js
```

The generator will work fine.

**Comment by gameFu** [comment]
+1

**Comment by stylesuxx** [comment]
You did run
```
yo react-webpack-redux
```

before running the generator for the action?

Please tell me your node and npm version too.

**Comment by Riokai** [comment]
@stylesuxx Yes,I confirm I was run `yo react-webpack-redux`
```shell
node -v
v5.6.0
npm -v
3.6.0
```

**Comment by stylesuxx** [comment]
Something must have gone wrong in:
```
yo react-webpack-redux
```

The files you are missing are created in the last step of running the above command.
Could you maybe rerun the command in a new folder and post the complete output.

**Comment by Riokai** [comment]
I understand. I press ctrl+c `react-webpack-redux` when it start process `npm install`, because I thouhgt it already generate all files (eg:src/reducers/index.js,src/containers/App.js).

**Comment by Riokai** [comment]
@stylesuxx I understand. I press ctrl+c react-webpack-redux when it start process npm install, because I thouhgt it already generate all files (eg:src/reducers/index.js,src/containers/App.js).

**Comment by stylesuxx** [comment]
Nope, you need to let it run to the end. Please report if this fixes the problem.

**Comment by Riokai** [comment]
Yes,It is works great.Thanks for your answer!
![qq20160324-0 2x](https://cloud.githubusercontent.com/assets/7970372/14015189/33974e34-f1f2-11e5-96d7-42b9532e1aaf.png)

**Comment by stylesuxx** [comment]
Happy to help.
I am closing this issue now.
