### ISSUE TITLE
can't generator store and container 

### ISSUE THREAD

**Issue by gameFu** [stylesuxx/generator-react-webpack-redux#21]
![image](https://cloud.githubusercontent.com/assets/11696134/14012578/934f4b4e-f1e1-11e5-8db3-87572a0ea740.png)

**Comment by stylesuxx** [comment]
Looks like you did not install the generator.
Does it appear in your lists of generators if you run:
```
yo --generators
```

**Comment by gameFu** [comment]
yes , I really don't see  store and container generator after I run `yo --generators`. Shouldn't they already have? 
![image](https://cloud.githubusercontent.com/assets/11696134/14021476/99ab4a1c-f216-11e5-8cfb-6faabbfbc25a.png)

**Comment by stylesuxx** [comment]
Ahh sorry, I did not pay attention on the generators you were trying to use.

There is no container genrator yet - it is on the Todo list.
Also I did not wire throught the store generator from the base generator.

**Comment by stylesuxx** [comment]
Added generator for containers in the current version (0.7.0)
Closing this down. Feel free to comment if you still have questions.
