### ISSUE TITLE
React router - which one to use ?

### ISSUE THREAD

**Issue by l1br3** [stylesuxx/generator-react-webpack-redux#22]
I know at least 3 routers for redux and I would like to know which one you plan to use in the generator.

[react-router-redux - provided by reactjs](https://github.com/reactjs/react-router-redux)
[redux-router - an alternative router with some differences](https://github.com/acdlite/redux-router)
[redux-tiny-router - I did not read the doc](https://github.com/Agamennon/redux-tiny-router)

**Comment by stylesuxx** [comment]
To be honest I have not decided yet.
But I tend to react-router-redux.

With redux-router they write it is experimental, so I am not sure about this.
Redux tiny router does not seem to be active anymore. At least when I look at the issues and PR's there does not seem to be happening too much,...

**Comment by prisonier** [comment]
I also tend to react-router-redux because of biggest community

**Comment by stylesuxx** [comment]
Lets leave this issue open for further discussion.

**Comment by stylesuxx** [comment]
Just a reminder for myself:
`react-router` does not support hot reloading.
`react-router-redux` is just a wrapper for `react-router` but also provides time travelling functionality for the redux store. Still will have the same *problem* with not being hot reloadable.

So the routes should most probably be in a separate container that is excluded from hot reloading.

**Comment by stylesuxx** [comment]
Closing this in favor of #1 where most of the discussion seems to be happening.
