### ISSUE TITLE
Add a namespace to main generator for easy integration with existing projects

### ISSUE THREAD

**Issue by prisonier** [stylesuxx/generator-react-webpack-redux#23]
Hi,

I recently bought a theme for react which has a specific architecture.
I would like to be able to use the genrator.

The `/src` theme architecture : 
```
src
├── jsx
│ ├── app
│ │ ├── redux
│ │ │ ├── actions
│ │ │ ├── reducers
```

I can copy/paste a freshly generated app inside a `src/jsx/app/redux/container` folder but the problem is when I will try to use sub generators. 
I can namespace them to put them in right folders but they will try to write in the App.js file.

Do you think you could add some parameter somewhere to be able able to change thoses paths ? 

[appPath in action generator](https://github.com/stylesuxx/generator-react-webpack-redux/blob/master/generators/action/index.js#L68)
[destination in action generator](https://github.com/stylesuxx/generator-react-webpack-redux/blob/master/generators/action/index.js#L69)
[constPath in action generator](https://github.com/stylesuxx/generator-react-webpack-redux/blob/master/generators/action/index.js#L70) (I see that you finally decided to remove const file namespace)
[appPath in reducers generator](https://github.com/stylesuxx/generator-react-webpack-redux/blob/master/generators/reducer/index.js#L102)
[rootReducerPath in reducers generator](https://github.com/stylesuxx/generator-react-webpack-redux/blob/master/generators/reducer/index.js#L102)
[destination in reducers generator](https://github.com/stylesuxx/generator-react-webpack-redux/blob/master/generators/reducer/index.js#L104)

I could hardcode this in the generator but as it is globally installed I don't like the idea.

Or maybe you think about a better solution ? 

Maybe the better solution would be to just clone the repo, hardcode modification without any parametering and use it as another generator ? 

EDIT : For the moment I installed the generator locally and made hardcoded modifications, everything is working fine.

**Comment by prisonier** [comment]
Currently I installed the generator localy and made some hard coded modifications. Also copied from a fresh project `reducers/index.js`, `containers/App.js` and `actions/const.js` and I'm able to use sub generators.

**Comment by stylesuxx** [comment]
Technically it should be possible to do this via `.yo-rc.json`. But to be honest, I am not sure if I really want this to be in the generator. I fear I will then have a lot of issues regarding wrong setup of this paths. Also for example the components generator is part of the base generator, and I can't really change those paths easily.

So I am not sure if it would not be better to fork this generator and make the adaptions.

Maybe you could link me to the react theme you bought - I did not even know that one could buy react themes.

**Comment by prisonier** [comment]
After playing with the theme, I can confirm that it won't be so much usefull to make so much modifications to the genrator. 

[The theme](https://wrapbootstrap.com/theme/rubix-reactjs-powered-admin-template-WB09498FH)
