### ISSUE TITLE
Unable to run unit test for Async Action Creators 

### ISSUE THREAD

**Issue by ankitaparekh** [stylesuxx/generator-react-webpack-redux#25]
Hello, I am trying to run unit tests for my async request. I am referring to http://redux.js.org/docs/recipes/WritingTests.htmlAsync Action Creators tutorial.

My test is:

    describe('async actions', () =>  {
    afterEach(() => {
      nock.cleanAll()
    })

    it('creates fetchAllDataAction call', (done) => {
      const requesting = false;
      nock('http://localhost:7788/')
        .get('/data/Data1')
        .reply(200,{ objects: { name: 'Test1'} } )
        .get('/Data2')
        .reply(200,{ objects: { name: 'Test2'} })
        .get('/Data3')
        .reply(200,{ objects: { name: 'Test3'} });

      const expectedActions = [
        { type: RECEIVE_DATA1 , objects: { name: 'Test1'}},
        { type: RECEIVE_DATA2 , objects: { name: 'Test2'}},
        { type: RECEIVE_DATA3 , objects: { name: 'Test3'} },
        { type: REQUEST_DATA3 , requesting},
      ]

      const store_mock = mockStore({},expectedActions,done)
      store_mock.dispatch(fetchAllData())
        .then(() => { // return of async actions
          expect(store_mock.getActions()).toEqual(expectedActions)
        })
        .then(done) 
        .catch(done)
        })
      })
    })

My action function is:
 ```
 export function fetchAllData(){
    return dispatch => {
      return $.getJSON(`${SERVER_ROOT}/data/Data1`)
        .then(json => {
          dispatch(receiveData1(json));
          $.getJSON(`${SERVER_ROOT}/Data2`)
            .then(json => {
              dispatch(receiveData2(json));
              $.getJSON(`${SERVER_ROOT}/Data3`)
                .then(json => {
                  dispatch(receiveData3(json));
                  dispatch(requestData3(false));
                });
            });
        });
    }
  }


function receiveData1(data){
 return { type: RECEIVE_DATA1,
          data: data
        }
}

function receiveData2(data){
 return { type: RECEIVE_DATA2,
          data
        }
}

function receiveData3(data){
 return { type: RECEIVE_DATA3,
          data
        }
 }

function requestData3(state){
 return { type: REQUEST_DATA3,
          state
        }
}
```

I keep getting the error  undefined is not a constructor (near '....catch(done); ...')
So tried to see if my nock works fine.So i ran the below test but i got following error.

    describe('async actions1', () => {
    beforeEach(() => {
      nock('http://localhost:7788')
        .get('/').reply(200, {data: 'yo'})
    })

    afterEach(() => {
      nock.cleanAll()
    })

    it('creates fetchAllData call', (done) => {
      const requesting = false;

    fetch('http://localhost:7788', { method: 'get' }).then(function(response) {
      console.log("Nock runs fine")
      done();
    }).catch(function(err) {
      console.log("error is :" +err)
      done();
    });
    })
    })

I get the error:LOG: 'error is :TypeError: Network request failed'
I am not sure what wrong I am doing here.I am very new to front end testing.
it would be great if someone could help me with this.

Thank you for your time and help.

**Comment by stylesuxx** [comment]
Do you still have an issues with this. I have some time and might look into this if help is still needed. Not sure how this is related to the generator though...

**Comment by stylesuxx** [comment]
Closing this for now, feel free to reopen if you still need help.
