### ISSUE TITLE
installation of dependancies

### ISSUE THREAD

**Issue by swarajd** [stylesuxx/generator-react-webpack-redux#3]
after running `npm install -g generator-react-webpack-redux` I still had to install readable-stream, once, inherits, colors, setimmediate, clone, diff, and possibly others until I manually installed generator-react-webpack. I believe these dependancies should be installed with the installation of this generator, however that was not the case.

**Comment by stylesuxx** [comment]
Interesting, *generator-react-webpack* is a dependency and should have been installed when installing this generator.
Can you maybe tell me the exact steps you took during installation and possible errors that you encountered.

**Comment by swarajd** [comment]
I ran the command "npm install -g generator-react-webpack-redux, which after installation, *said* generator-react-webpack was installed, but in reality it wasn't. After installation, I tried to run the command "yo react-webpack-redux," and it started displaying error messages saying the aforementioned packages in the issue were not installed.

**Comment by stylesuxx** [comment]
Can you please post the yo, npm and node version you are using, I can then try to reproduce it in a VM.
```Bash
npm --version
yo --version
node --version
```

**Comment by swarajd** [comment]
sorry for getting back to you so late, the versions are: 2.14.4, 1.6.0, and v4.1.1

**Comment by stylesuxx** [comment]
No problem I have time ;-)
Thanks for posting. Just as reference. My current setup is
npm: 3.5.2
yo: 1.5.1
node: 4.2.4

I will see if I can reproduce it - hope to get back to you in a couple of days.

**Comment by stylesuxx** [comment]
npm: 2.14.4
yo: 1.6.0
node: v4.1.1

```Bash
sudo npm remove generator-react-webpack-redux -g
sudo npm install generator-react-webpack-redux -g
```
Installs without problems

```Bash
mkdir testing
cd testing
yo react-webpack-redux
npm start
```

Scaffolds and starts without any problems. Maybe you can do ma a favor and run the above commands and post the *whole* log.

**Comment by swarajd** [comment]
That's strange. I guess it must just be my system then.
