### ISSUE TITLE
Need sample 

### ISSUE THREAD

**Issue by ericjong** [stylesuxx/generator-react-webpack-redux#30]
Hi @stylesuxx , thank you for the awesome generator.

I am having some problems starting a new project. As a start, I'm going to create a button & label control.
Based on button click, I'm going to show/hide label control.
I was able to create actions & reducers but onClick is not triggering actions.
![image](https://cloud.githubusercontent.com/assets/18637526/16705833/6ccac35a-454b-11e6-893e-733a7acb80ac.png)

I get this error refresh the page. 

Do you mind upload the sample project where actions, reducers & state changes are working?

Thank you

**Comment by stylesuxx** [comment]
Please take a look at the [example branch](https://github.com/stylesuxx/generator-react-webpack-redux/tree/feature/examples).

Let me know if that helps.

**Comment by stylesuxx** [comment]
I am closing this question for lack of activity, feel free to re open.
