### ISSUE TITLE
 Actions must be plain objects. Use custom middleware for async actions.

### ISSUE THREAD

**Issue by Philin-Anton** [stylesuxx/generator-react-webpack-redux#35]
I try run action that sends a request to the server and return should run "dispatch" and displays an error "Actions must be plain objects. Use custom middleware for async actions."
stores/index.js

> import {
  createStore,
  applyMiddleware
} from 'redux';
import reducers from '../reducers/index';
import logger from 'redux-logger';
import thunk from 'redux-thunk';
module.exports = function(initialState) {
  const middleware = process.env.NODE_ENV === 'production' ?
    [ thunk ] :
    [ thunk, logger() ];
  const store = applyMiddleware(...middleware)(createStore)(reducers, initialState);
  if (module.hot) {
    // Enable Webpack hot module replacement for reducers
    module.hot.accept('../reducers', () => {
      const nextReducer = require('../reducers');
      store.replaceReducer(nextReducer)
    })
  }
  return store
};

action.js

> export function Advertiser(dispatch) {
  return () => {
    //dispatch({ type: LOAD_START });
    return fetch.get('/api/advertisers/list.json').then(
        result => {
        dispatch(requestAdvertisers(result));
        //dispatch({ type: LOAD_END, payload: result });
        return result;
      },
      throwAjaxError
    );
  };
}

**Comment by stylesuxx** [comment]
Yeah, I currently do not have anything in place for async actions. You could use promises, or take a look [in the docs](http://redux.js.org/docs/advanced/AsyncFlow.html) where a couple of middleware options are listed.

**Comment by stylesuxx** [comment]
Closing this down for lack of activity. Feel free to reopen.
