### ISSUE TITLE
Unable to Create reducers and actions using the commands

### ISSUE THREAD

**Issue by Sreevenkateshn** [stylesuxx/generator-react-webpack-redux#37]
yo react-webpack-redux:reducer my/namespaced/reducers/name
yo react-webpack-redux:reducer items
yo react-webpack-redux:action my/namespaced/actions/name
yo react-webpack-redux:action items/addItem
I tried creating reducer with the above command and I was not able to create reducer

**Comment by stylesuxx** [comment]
Unfortunately this does not help me all too much. Please post some output from the console. Where did it go wrong exactly. Which node/npm/yeoman versions are you using?

**Comment by gorjuspixels** [comment]
This has been resolved http://status.npmjs.org/incidents/dw8cr1lwxkcr

**Comment by stylesuxx** [comment]
I am closing this down for lack of information. Feel free to reopen.
