### ISSUE TITLE
[question] How can I deploy with docker?

### ISSUE THREAD

**Issue by juegas** [stylesuxx/generator-react-webpack-redux#38]
Hey, all I'm at a point with my app where a staging/prod pipeline is in order. 

Docker is the hotness I want to use but I'm not sure where to start in regards to this generated app.  

So far my thoughts are Nginx + App.  Any advice would be much appreciated. 

I've been able to install docker for mac and understand the basics. I haven't been able to get my app to run within a running container. I am getting an image to build... but not properly I believe. 

Here's my dockerfile so far: [ [source used as starting off point](https://github.com/DEV3L/docker-node-js-webpack) ]

```
  0 FROM node:latest
  1
  2 COPY . /src
  3 WORKDIR /src
  4
  5 RUN npm install
  6 RUN npm rebuild node-sass
  7
  8 EXPOSE 8000
  9
 10 CMD [ "node", "server.js" ]
```

**Comment by stylesuxx** [comment]
I have not yet tried it with docker, so I can not really say anything about it. Did you get it to run in the mean time? Maybe I can find some time on the weekend to give it a whirl.

**Comment by stylesuxx** [comment]
Closing this down for lack of activity... Feel free to open with suggestions.
