### ISSUE TITLE
Can't create an action

### ISSUE THREAD

**Issue by andrzey** [stylesuxx/generator-react-webpack-redux#41]
I run npm version 3.10.6 and node version 6.2.2 and I can't create an action. Is this normal?

**Comment by raj-optisol** [comment]
Yes, also reducers not generating

**Comment by stylesuxx** [comment]
Can you provide more info - is there any error output?

**Comment by raj-adroit** [comment]
**Action generator and Reducer generator Not working**


Actually its not returning any error or info..

![screen shot 2016-09-12 at 12 03 00 pm](https://cloud.githubusercontent.com/assets/2361576/18426689/0abc400c-78e1-11e6-9334-b7699672e12b.png)

Component generate command works..
![screen shot 2016-09-12 at 12 03 21 pm](https://cloud.githubusercontent.com/assets/2361576/18426706/2590682c-78e1-11e6-807d-02ddf0fad9d4.png)

Am using Node v4.4.6, npm 2.15.5

**Comment by stylesuxx** [comment]
Hmm interesting. This is happening on a macbook I suppose. @andrzey are you on mac too by any chance?

@raj-adroit which version of the generator are you using? I updated it a couple of days ago to the new base template - maybe you could try the most recent version and report back.

If possible please also try try with node >=6.0.0

Does this happen with a freshly generated project? Or did you change anything?

There was a similar problem a bit ago,... seems the ast generator was making troubles, but on mac it did not throw errors when a file was missing. To help me debugging you could share a freshly generated project after running the action generator - I can then compare to the expected result.

**Comment by raj-adroit** [comment]
Looks like its working after upgrading to latest version 1.0.2, before i have used 0.8.0

Now generators working fine, am unable to start the app, because of some dependencies issue.

I have tried with both node v4.4.8 and node v.6.5.0

**Node v4.4.8**

![screen shot 2016-09-12 at 4 54 29 pm](https://cloud.githubusercontent.com/assets/2361576/18434653/1b1ef266-790c-11e6-9b12-ddfed0d80843.png)

**Node v.6.5.0**

![screen shot 2016-09-12 at 4 55 17 pm](https://cloud.githubusercontent.com/assets/2361576/18434666/303a1afe-790c-11e6-83f5-4e652babdf0b.png)

**Comment by stylesuxx** [comment]
Hmm, I just tried from scratch with node v.6.5.0 interestingly I get the same warning, but webpack is installed in /node/modules and I can run

    npm start

Not sure how to interpret that right now. Can you run the app? If not - are there any errors?

Means https://github.com/stylesuxx/generator-react-webpack-redux/issues/44 is related to old node version too.

**Comment by raj-adroit** [comment]
Cool, yes its showing warning but works.. with Node 6.5.0
( i have tried again with setting default alias for latest version in nvm)

But for older/LTS version of Node its not running and throw #44 error

**Comment by stylesuxx** [comment]
Hmm, I guess I should at least support from the last LTS version so from 4.5.0

So I just tried a setup with

    node -v
    v4.5.0
    
    npm -v
    3.10.7

and it is scaffolding fine. This means, that npm is the culprit.

Will check that v4.5.0 works with it's accoriding npm version.

**Comment by stylesuxx** [comment]
Fixed in 1.1.0 - feel free to re-open if problem persists.
