### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by georgelam0306** [stylesuxx/generator-react-webpack-redux#44]
seems to be failing on the new webpack

npm ERR! peerinvalid The package webpack@2.1.0-beta.22 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer babel-loader@6.2.5 wants webpack@1 || ^2.1.0-beta
npm ERR! peerinvalid Peer sass-loader@3.2.3 wants webpack@^1.12.6 || ^2.1.0-beta
npm ERR! peerinvalid Peer karma-webpack@1.8.0 wants webpack@^1.1.0 || ^2 || ^2.1.0-beta
npm ERR! peerinvalid Peer webpack-dev-server@2.0.0-beta wants webpack@>=2.0.3-beta <3

**Comment by stylesuxx** [comment]
At which point is this happening? Which version of npm are you using?

Please post output of:

    npm -v
    node -v

**Comment by stylesuxx** [comment]
OK, just published a new version of the generator. Please make sure you have at least node version 4.5.0 and npm version 3.0.0.

**Comment by netsi1964** [comment]
as @stylesuxx said you need NPM 3+ - I installed npm@next which helped me with this problem `npm install -g npm@next`

**Comment by georgelam0306** [comment]
`npm -v && node -v
3.10.8
v6.5.0`
i still get a warning
npm WARN webpack-dev-server@2.0.0-beta requires a peer of webpack@>=2.0.3-beta <3 but none was installed.

but the project runs now.
