### ISSUE TITLE
old npm module .

### ISSUE THREAD

**Issue by jiqimaogou** [stylesuxx/generator-react-webpack-redux#47]
npm WARN deprecated isparta-loader@2.0.0: This package is deprecated in favor of https://github.com/istanbuljs/babel-plugin-istanbul
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
npm WARN deprecated has-color@0.1.7: Renamed to supports-color. If you're using chalk, upgrade to the latest version. https://github.com/chalk/supports-color
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by stylesuxx** [comment]
Yep, I know of this, but those are not direct dependencies, but rather dependencies we are building on. One would need to trace them back to their root module.

I think some of them are coming from yeoman, like the jade and chalk dependency.
