### ISSUE TITLE
Cannot read property 'apply' of undefined(…)

### ISSUE THREAD

**Issue by mkim871** [stylesuxx/generator-react-webpack-redux#49]
I am getting an 'apply' of undefined error when I run `npm run dist` like below.
This is bit weird it is working fine when `npm start` but only shows an error when it comes to distribution mode.

compose.js is located at `webpack:///../~/redux/es/compose.js`

![screen shot 2016-10-28 at 1 47 58 pm](https://cloud.githubusercontent.com/assets/8052740/19790499/36173290-9d15-11e6-9677-b7a4864bb1de.png)

My file structure is like below

![screen shot 2016-10-28 at 1 48 57 pm](https://cloud.githubusercontent.com/assets/8052740/19790518/5820edd6-9d15-11e6-9246-3257ef79584f.png)

I also edited alias path like below

![screen shot 2016-10-28 at 1 49 15 pm](https://cloud.githubusercontent.com/assets/8052740/19790519/591d585a-9d15-11e6-9c6d-ce9c55fb7000.png)

What would be the problem?

**Comment by stylesuxx** [comment]
Hey, I can not reproduce this. Could you maybe share the project this is happening with? Also please check the newest generator version 1.1.0 and see if that fixes it for you.

**Comment by stylesuxx** [comment]
Closing this down for lack of activity, feel free to open any time with more information.
