### ISSUE TITLE
allow console in dev env

### ISSUE THREAD

**Issue by tryer3000** [stylesuxx/generator-react-webpack-redux#5]
got 'unexpected console statement' while developing.

**Comment by stylesuxx** [comment]
Jup, this is just a warning from the linter. If you want to use **console** you can disable this linting rule in *.eslintrc*

I would suggest using the **[debugger](http://www.w3schools.com/jsref/jsref_debugger.asp)** statement instead.

You might also want to check out the [react dev tools for chrome](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) and the [Redux DevTools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd).

**Comment by tryer3000** [comment]
:+1: 
Thank you for these tips, TIL
