### ISSUE TITLE
 .scss files are not working when we choose scss while doing project setup

### ISSUE THREAD

**Issue by bairisuresh** [stylesuxx/generator-react-webpack-redux#57]
Hi,
While doing project setup i have choosen .scss but when i generate any component it is creating the css files with filename.cssmodule.scss.
When i write any css in .scss file it is not working
please let me know is it the expected behavior of base generator.

**Comment by stylesuxx** [comment]
Hey @bairisuresh no, this is not expected behavior and is now fixed in the develop branch, thank you for pointing this out.

**Comment by stylesuxx** [comment]
Fixed in 1.1.0 - feel free to re-open if problem persists.
