### ISSUE TITLE
What exactly do App.js and run.js do?

### ISSUE THREAD

**Issue by tconroy** [stylesuxx/generator-react-webpack-redux#6]
Hi -- I'm still very new to React/Redux so apologies if this is a poor question. However I'm having a difficult time understanding exactly what these two files are doing in the generator.

I've started a fresh project and simply added a `console.log(this);` to the render method of App.js and run.js, and neither appears to be executed when the app runs. 

If I do the same inside `Main.js` render function, I get the component logged out.

What do these files do, and why does it appear that editing them has zero affect on the application?

**Comment by stylesuxx** [comment]
Hey @tconroy,
which version of the generator are you using, please upgrade to *0.5.0*
The template, I am depending on was updated and does no longer use run.js as the entry point, this is why you are not seeing your console logs. This should be fixed in version *0.5.0* though.

**Comment by tconroy** [comment]
Hi @stylesuxx, 
thanks for the quick reply. :) Indeed it seems I was on an old version -- which is really weird since I only ran `npm install -g generator-webpack-redux` last night! Is the default install an older version? 

I updated the generator just now and started a new project, and run.js has disappeared and I'm getting log output from App.js. Sweet! 

Does this mean the Provider has been removed from the generator?

**Comment by stylesuxx** [comment]
No it is still there. Formerly run.js was the entry point to the app, but now index.js is the entry point to the app, this is also the place where the Provider lives now.

Not sure about why you got the "old version", but I only released it two days ago,...

**Comment by tconroy** [comment]
Oh I see! Excellent. Thank you for your help + great work on this generator!

Cheers.
