### ISSUE TITLE
client.js/index.js relationship, impossible to access store

### ISSUE THREAD

**Issue by obsidianart** [stylesuxx/generator-react-webpack-redux#60]
containers/App.js seems the connection point to the reducer, but it is only include in index.js

client.js seems the entry point during dev, which points directly to components/app.js

I can't access the store as I'm using directly component/app.js (which is stateless)

I tried to modify this way but both components expect a single root and I'm not sure what is the proper way
```
  <AppContainer>
    <Provider store={store}>
      <App />
    </Provider>
  </AppContainer>,
```

Also, it would be nice to add a note about how to use previous generator version, I have to teach React from time to time and solving a problem like this in a class is quite complicated (whatever it is a bug or not, I got stuck for more than an hour now and I'm giving up).

**Comment by stylesuxx** [comment]
Hey, this is related to this issue => https://github.com/stylesuxx/generator-react-webpack-redux/issues/56 which I fixed in develop, closing down here.
