### ISSUE TITLE
webpack version is too low

### ISSUE THREAD

**Issue by NuoManDai** [stylesuxx/generator-react-webpack-redux#64]
I am in npm start these problems.
Suggest the authors to upgrade webpack 2.2.1 or run npm update.

C:\Users\john_\Desktop\react-redux-dom\yo-demo\node_modules\webpack-dev-server\bin\webpack-dev-server.js:386
                throw e;
                ^

TypeError: webpack.validateSchema is not a function
    at new Server (C:\Users\john_\Desktop\react-redux-dom\yo-demo\node_modules\webpack-dev-server\lib\Server.js:25:35)
    at startDevServer (C:\Users\john_\Desktop\react-redux-dom\yo-demo\node_modules\webpack-dev-server\bin\webpack-dev-server.js:379:12)
    at processOptions (C:\Users\john_\Desktop\react-redux-dom\yo-demo\node_modules\webpack-dev-server\bin\webpack-dev-server.js:317:3)
    at Object.<anonymous> (C:\Users\john_\Desktop\react-redux-dom\yo-demo\node_modules\webpack-dev-server\bin\webpack-dev-server.js:441:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

**Comment by stylesuxx** [comment]
This happens after you freshly generate a project and then run **npm strart**?

To me this looks like you are using an old version of the generator. Could you post the content of **package.json** ?

**Comment by NuoManDai** [comment]
Yes,my freshly generate a project and then run npm strart。
The dependence of webpack and local generator-react-webpack the relevant?

   "devDependencies": {
    "babel-core": "^6.7.6",
    "babel-eslint": "^7.1.0",
    "babel-loader": "^6.2.4",
    "babel-plugin-istanbul": "^3.0.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-object-rest-spread": "^6.8.0",
    "babel-polyfill": "^6.9.0",
    "babel-preset-airbnb": "^2.0.0",
    "babel-preset-es2015-native-modules": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "chai": "^3.5.0",
    "copyfiles": "^1.0.0",
    "css-loader": "^0.26.0",
    "enzyme": "^2.2.0",
    "eslint": "^3.0.0",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-loader": "^1.3.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^2.2.0",
    "eslint-plugin-react": "^6.0.0",
    "file-loader": "^0.9.0",
    "karma": "^1.0.0",
    "karma-chai": "^0.1.0",
    "karma-coverage": "^1.0.0",
    "karma-junit-reporter": "^1.0.0",
    "karma-mocha": "^1.0.1",
    "karma-mocha-reporter": "^2.0.3",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-sinon": "^1.0.5",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^1.7.0",
    "mocha": "^3.0.0",
    "null-loader": "^0.1.1",
    "phantomjs-prebuilt": "^2.1.7",
    "postcss": "^5.0.21",
    "postcss-loader": "^0.9.1",
    "react-addons-test-utils": "^15.0.1",
    "rimraf": "^2.5.2",
    "sinon": "^1.17.3",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "webpack": "^2.1.0-beta.6",
    "webpack-dev-server": "^2.1.0-beta"
  },
  "dependencies": {
    "cross-env": "^3.1.0",
    "react": "^15.0.1",
    "react-dom": "^15.0.1",
    "react-hot-loader": "^3.0.0-beta.6",
    "react-redux": "^5.0.2",
    "redux": "^3.6.0",
    "webpack": "^2.1.0-beta.6"
  }

**Comment by NuoManDai** [comment]
"webpack": "^2.1.0-beta.6"

**Comment by stylesuxx** [comment]
Hmm, this looks OK.
We want at least v2.1.0-beta.6  
When I run the generator I get version v2.2.1 of webpack installed.

Did you run npm update as suggested in the hint?

**Comment by linkeyd** [comment]
At the time of operation failure.
I run npm update.
Successful runs again.
I just want to this problem.

**Comment by stylesuxx** [comment]
Sorry, could you maybe re-phrase, I did not understand the last part.

**Comment by linkeyd** [comment]
Yes. I suggest to add run npm update hint.
