### ISSUE TITLE
I get a 'Failed to load resource: net::ERR_FILE_NOT_FOUND' in index.html dist folder

### ISSUE THREAD

**Issue by codestitch** [stylesuxx/generator-react-webpack-redux#66]
After doing `npm run dist` and then opening index.html in dist folder I got the error 'Failed to load resource: net::ERR_FILE_NOT_FOUND'.

project url: https://github.com/codestitch/dashboard-material

i check on the network (inspect element) and i guess it didn't find app.js.

Please help me w/ the issue.

Thank you

**Comment by codestitch** [comment]
I also tried to create a new project and use the generator. After that I run `npm run dist` and open index.html at dist folder and got the same issue. 

Is there anything I would do before running dist?

Thank you.

**Comment by stylesuxx** [comment]
Are you serving the file properly, or just accessing it via file browser?

you can serve your dist files by running `npm run serve:dist`

If you want to serve your app from github you can do this by using the gh-pages branch and deploying the content of your dist directory there.

I did it here the exact same way with a [project of mine](https://github.com/stylesuxx/LiftOff-Track-and-Race-Generator). This is what the [gh-pages branch](https://github.com/stylesuxx/LiftOff-Track-and-Race-Generator/tree/gh-pages) should look like, and the result on [stylesuxx.github.io/LiftOff-Track-and-Race-Generator](https://stylesuxx.github.io/LiftOff-Track-and-Race-Generator/).

**Comment by codestitch** [comment]
Hi sir @stylesuxx. Thank you for responding to my issue. I am newbie reactjs, redux and setup.

Yes, after running `npm run dist` I open the file (index.html) via browser (chrome) and got this result:

<img width="1280" alt="screen shot 2017-02-10 at 9 50 40 pm" src="https://cloud.githubusercontent.com/assets/5573444/22829019/4981a2de-efdb-11e6-825f-644cceca0f3d.png">

and also in my public server:

<img width="500" alt="screen shot 2017-02-10 at 9 57 01 pm" src="https://cloud.githubusercontent.com/assets/5573444/22829135/fc294e0a-efdb-11e6-8a9d-4aa71d524623.png">

I was thinking that when you run `npm run dist` your project will be compiled and minified and then you can run it on browser or put it in the server and then run it (like in my public server) like what is stated in <a href='http://yeoman.io/codelab/prepare-production.html'>yeoman website</a>.

**Comment by stylesuxx** [comment]
If you are not serving from the top level (you are in a folder), you need to adjust the path to app.js in index.html

Change this line:
`<script type="text/javascript" src="/assets/app.js"></script>`

to this:
`<script type="text/javascript" src="./assets/app.js"></script>`

this way it will import relative to your index.html

Do the same with the path to the favicon.

**Comment by codestitch** [comment]
I changed it to 
`<script type="text/javascript" src="./assets/app.js"></script>`

<img width="750" alt="screen shot 2017-02-10 at 10 29 07 pm" src="https://cloud.githubusercontent.com/assets/5573444/22830218/a01710ca-efe0-11e6-877f-5f03d31de6da.png">

but still got a blank page.

I should be seeing this.

<img width="750" alt="screen shot 2017-02-10 at 10 30 13 pm" src="https://cloud.githubusercontent.com/assets/5573444/22830248/c0fbc02e-efe0-11e6-84ff-faca1062dc21.png">

**Comment by stylesuxx** [comment]
I just cloned your repo, adjusted the path, ran 
`npm run dist`
`npm run serve:dist`

Also tried serving it with python one liner (from within the dist folder):
`python -m SimpleHTTPServer 12345`

and it is behaving as expected.

![screenshot from 2017-02-10 16-00-10](https://cloud.githubusercontent.com/assets/978192/22831364/6d18a6a6-efaa-11e6-8aab-11058499fae2.png)

Might be an issue with the router when the app is not properly served. You are only accessing it via file browser and not serving it.

**Comment by codestitch** [comment]
What do you suggest sir to do? I'm bit confused because when I debug the app via `npm run serve` it works fine.

**Comment by stylesuxx** [comment]
Well, like I said before, simply serve it any way you want and you should be OK.
I do not know your setup, but I provided a solution to serve it with python. As long as your path is correct you should be able to serve it with any http server...

**Comment by codestitch** [comment]
Hello sir.

I tried to create a fresh new react-webpack-redux project and there something I notice with routing w/c I don't have idea how to solve.

First scenario: Without Router Compilation. Compiled using `npm run dist`. Copied the files from dist folder and placed in my htdocs in my public server (using xampp).

![test1](https://cloud.githubusercontent.com/assets/5573444/22869557/069ca976-f1db-11e6-96fb-adcfb5628169.PNG)

works fine. Also works fine in my local Drive C:

![test2](https://cloud.githubusercontent.com/assets/5573444/22869577/2ded910c-f1db-11e6-823a-a1985952d73d.PNG)

Now when I use React-Router (I followed in your wiki - added IndexRoute).

![test6](https://cloud.githubusercontent.com/assets/5573444/22869704/f0abe7a2-f1db-11e6-851e-aad46d5ad320.PNG)

It worked on localhost:8000 w/ the command `npm run serve`. It worked on localhost:8000 w/ the command `npm run serve`.

![test3](https://cloud.githubusercontent.com/assets/5573444/22869715/0ba06768-f1dc-11e6-84a3-ed6def60e71d.PNG)

Now when I compile to production. `npm run dist` and then same thing copy the files from /dist folder and place in my public server (same as the first scenario) inside htdocs folder. 

![test5](https://cloud.githubusercontent.com/assets/5573444/22869760/54c0dc2a-f1dc-11e6-9d26-8a89a5d7ada3.PNG)

It won't run. Same in my local drive.

![test4](https://cloud.githubusercontent.com/assets/5573444/22869769/6211e6bc-f1dc-11e6-97a4-077be96bb7a2.PNG)

Am I missing something when using Routes? Or do i need to configure something in my public server (I'm using xampp).

 I hope you can help me on this.

Thank you.

**Comment by codestitch** [comment]
Hi. I was able to fix the problem by using 

`const browserHistory = useBasename(createHistory)({
     basename: "/myapp"
 });`

Though I'm still having problems with `browserHistory.push('/')` or `browserHistory.push('/myapp')`, because it is not redirecting to home page after login.

Anyway, thank you. The problem for this issue is fixed.

**Comment by mr-palindrome** [comment]
Hii,
I'm also getting the same problem!!
Please help me out...
The image bg.png is not visible!!
Showing the same error "Failed to load resource: net::ERR_FILE_NOT_FOUND".
![gt2](https://user-images.githubusercontent.com/56421861/68879859-293e6100-0730-11ea-8181-bae4612e48d3.png)
![git](https://user-images.githubusercontent.com/56421861/68879882-31969c00-0730-11ea-850d-9b548e85ca88.png)

**Comment by Mahmoud-farargy** [comment]
I have the same problem, I followed tutorials and step by step guides but it still doesn't work with me. Please help!!
