### ISSUE TITLE
Object not found! - Error 404 when refreshing page link - dist mode

### ISSUE THREAD

**Issue by codestitch** [stylesuxx/generator-react-webpack-redux#67]
Hi all!.

In /dist folder, i run my distribution mode app and all seems alright. However, one problem occurred w/c is when i navigate to a link (say /push) and then reload it afterwards this error occur.

![capture](https://cloud.githubusercontent.com/assets/5573444/22960003/9ac153e0-f375-11e6-8858-4514c9d13437.PNG)

I'm using xampp as my server. 

What should I do with this?

Thank you.

**Comment by codestitch** [comment]
solved by:

http://stackoverflow.com/questions/32150653/apache-web-server-doesnt-allow-me-to-refresh-on-about-but-on-localhost-its-wor#_=_

Thanks.

**Comment by stylesuxx** [comment]
Thank you.  I need to go through your posts and update the Info regarding routing :-)

**Comment by shriIT** [comment]
> Hi all!.
> 
> In /dist folder, i run my distribution mode app and all seems alright. However, one problem occurred w/c is when i navigate to a link (say /push) and then reload it afterwards this error occur.
> 
> ![capture](https://cloud.githubusercontent.com/assets/5573444/22960003/9ac153e0-f375-11e6-8858-4514c9d13437.PNG)
> 
> I'm using xampp as my server.
> 
> What should I do with this?
> 
> Thank you.

same issue in my project. How to solve please help me

**Comment by shriIT** [comment]
Hello Sir, I am facing some issue in my project, i have used BrowserRouter for Route but after create build then run on browser and after refresh page 'object not found error showing' but i have used HashRouter for Route then after create build run on browser, project run perfect. Please help me to solve this error 'object not found after page refresh'
