### ISSUE TITLE
I'm getting fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by tomgron** [stylesuxx/generator-react-webpack-redux#68]
OS Win 10,
latest node, latest yoman
command to execute : npm install -g generator-react-webpack-redux

Error stack :

C:\temp> npm install -g generator-react-webpack-redux
npm ERR! git clone C:\Users\TommiGrönlund\AppData\Roaming\npm-cache\_git-remotes\git-github-com-react-webpack-generators-generator-react-webpack-git-master-a7b54b2a c:\temp\npm-10064-17df
bcae\git-cache-780f4bef\9c682541787602290fc6d115d90dbd3386cfda10: Cloning into 'c:\temp\npm-10064-17dfbcae\git-cache-780f4bef\9c682541787602290fc6d115d90dbd3386cfda10'...
npm ERR! git clone C:\Users\TommiGrönlund\AppData\Roaming\npm-cache\_git-remotes\git-github-com-react-webpack-generators-generator-react-webpack-git-master-a7b54b2a c:\temp\npm-10064-17df
bcae\git-cache-780f4bef\9c682541787602290fc6d115d90dbd3386cfda10: "git-upload-pack 'C:\Users\TommiGrönlund\AppData\Roaming\npm-cache\_git-remotes\git-github-com-react-webpack-generators-g
enerator-react-webpack-git-master-a7b54b2a'": git-upload-pack 'C:\Users\TommiGrönlund\AppData\Roaming\npm-cache\_git-remotes\git-github-com-react-webpack-generators-generator-react-webpac
k-git-master-a7b54b2a': No such file or directory
npm ERR! git clone C:\Users\TommiGrönlund\AppData\Roaming\npm-cache\_git-remotes\git-github-com-react-webpack-generators-generator-react-webpack-git-master-a7b54b2a c:\temp\npm-10064-17df
bcae\git-cache-780f4bef\9c682541787602290fc6d115d90dbd3386cfda10: fatal: Could not read from remote repository.
npm ERR! git clone C:\Users\TommiGrönlund\AppData\Roaming\npm-cache\_git-remotes\git-github-com-react-webpack-generators-generator-react-webpack-git-master-a7b54b2a c:\temp\npm-10064-17df
bcae\git-cache-780f4bef\9c682541787602290fc6d115d90dbd3386cfda10:
npm ERR! git clone C:\Users\TommiGrönlund\AppData\Roaming\npm-cache\_git-remotes\git-github-com-react-webpack-generators-generator-react-webpack-git-master-a7b54b2a c:\temp\npm-10064-17df
bcae\git-cache-780f4bef\9c682541787602290fc6d115d90dbd3386cfda10: Please make sure you have the correct access rights
npm ERR! git clone C:\Users\TommiGrönlund\AppData\Roaming\npm-cache\_git-remotes\git-github-com-react-webpack-generators-generator-react-webpack-git-master-a7b54b2a c:\temp\npm-10064-17df
bcae\git-cache-780f4bef\9c682541787602290fc6d115d90dbd3386cfda10: and the repository exists.
npm ERR! git clone C:\Users\TommiGrönlund\AppData\Roaming\npm-cache\_git-remotes\git-github-com-react-webpack-generators-generator-react-webpack-git-master-a7b54b2a c:\temp\npm-10064-17df
bcae\git-cache-780f4bef\9c682541787602290fc6d115d90dbd3386cfda10:
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "generator-react-webpack-redux"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone C:\Users\TommiGrönlund\AppData\Roaming\npm-cache\_git-remotes\git-github-com-react-webpack-generators-generator-react-webpack-git
-master-a7b54b2a c:\temp\npm-10064-17dfbcae\git-cache-780f4bef\9c682541787602290fc6d115d90dbd3386cfda10
npm ERR! Cloning into 'c:\temp\npm-10064-17dfbcae\git-cache-780f4bef\9c682541787602290fc6d115d90dbd3386cfda10'...
npm ERR! "git-upload-pack 'C:\Users\TommiGrönlund\AppData\Roaming\npm-cache\_git-remotes\git-github-com-react-webpack-generators-generator-react-webpack-git-master-a7b54b2a'": git-upload-
pack 'C:\Users\TommiGrönlund\AppData\Roaming\npm-cache\_git-remotes\git-github-com-react-webpack-generators-generator-react-webpack-git-master-a7b54b2a': No such file or directory
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\temp\npm-debug.log
C:\temp>

**Comment by stylesuxx** [comment]
Hmm, interesting.
I am wondering, since you are installing the generator globally, are you running the commands as admin? Or do you have something like nvm set up?

my experience with Windows is very limited - so this may take some time,...

Please also post your npm version.
`npm --version`

**Comment by tomgron** [comment]
npm --version gives me 4.0.5 where it didn't work but it works on another machine with version of 4.1.2. Both Windows (10 and 2016 server)

**Comment by tomgron** [comment]
This gets to work when reinstalling node
