### ISSUE TITLE
npm start have a error?

### ISSUE THREAD

**Issue by luojinghui** [stylesuxx/generator-react-webpack-redux#77]
```
ERROR in ./client.js
Module parse failed: /Users/luojinghui/projects/react-questions/src/client.js Unexpected token (11:2)
You may need an appropriate loader to handle this file type.
|
| ReactDOM.render(
|   <AppContainer>
|     <Provider store={store}>
|       <App />
 @ multi main
```
how to resolve?

**Comment by raza2022** [comment]
@luojinghui it's about missing a loader in config as i think.

- make sure your `npm install` successes without any errors.
- if you changed any other module version then delete node modules folder and run fresh `npm i` agian
hopes it will solve the problem

**Comment by luojinghui** [comment]
@raza2022 ok，I re-executed `npm install`,then it's working.thanks

**Comment by raza2022** [comment]
@luojinghui great so you can close the issue as well
