### ISSUE TITLE
Error running after generating with sass options

### ISSUE THREAD

**Issue by codestitch** [stylesuxx/generator-react-webpack-redux#84]
Hi. I followed these procedures from installing `npm install -g yo` and `npm install -g generator-react-webpack-redux` to running `yo react-webpack-redux`. 

Here's the config I choose:
 style: **scss**
 enable css module support: **no**
 enable postcss: **yes**

After running `npm run start` I got an error for post css. Here's the error:

`Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 configuration has an unknown property 'postcss'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           postcss: ...
         }
       })
     ]`

**Comment by MarcoScabbiolo** [comment]
Refer to [this comment](https://github.com/stylesuxx/generator-react-webpack-redux/issues/70#issuecomment-298575764) on #70 to solve this problem.

**Comment by codestitch** [comment]
Thank you.
